# Generated by Django 4.2.6 on 2023-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_student_id_alter_student_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
