# Generated by Django 4.2.6 on 2023-11-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='card_id',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='card_id',
            field=models.CharField(default='0', max_length=20, primary_key=True, serialize=False),
        ),
    ]
